# Runtime Lambda configuration
spring.profiles.include=core

# Spring Cloud Function configuration
spring.cloud.function.definition=runtimeRouter

# Logging configuration
logging.level.nl.vintik.mocknest.infra.aws.runtime=DEBUG
