# Runtime Lambda configuration
spring.profiles.include=core

# Spring Cloud Function configuration
spring.cloud.function.definition=runtimeRouter

# S3 Configuration
storage.bucket.name=${MOCKNEST_S3_BUCKET_NAME:mocknest-serverless-storage}

# Logging configuration
logging.level.nl.vintik.mocknest.infra.aws.runtime=DEBUG
