# AWS Configuration
aws.region=${AWS_REGION:eu-west-1}

# S3 Configuration
storage.bucket.name=${MOCKNEST_S3_BUCKET_NAME:mocknest-serverless-storage}

# Application Configuration
spring.application.name=mocknest-serverless

# Spring Cloud Function configuration
spring.cloud.function.definition=router