# AWS Configuration

aws.region=${MOCKNEST_APP_REGION:${AWS_REGION:eu-west-1}}
bedrock.inference.prefix=${BEDROCK_INFERENCE_PREFIX:eu}
bedrock.model.name=${BEDROCK_MODEL_NAME:AmazonNovaPro}

# S3 Configuration
storage.bucket.name=${MOCKNEST_S3_BUCKET_NAME:mocknest-serverless-storage}

# Application Configuration
spring.application.name=mocknest-serverless

# Spring Cloud Function configuration
spring.cloud.function.definition=router