name: Main Branch AWS Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/workflow-build.yml

  deploy:
    needs: test
    uses: ./.github/workflows/workflow-deploy-aws.yml
    with:
      environment: staging
      aws-region: 'eu-west-1'
      github-actions-role-name: 'GitHubOIDCAdmin'  # Change this to your existing role name
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}